config/routes.rb
BnrAmhillNet::Application.routes.draw do
  root :to => 'people#index'

  get 'signin' => 'session#new'
  post 'signin' => 'session#create'
  delete 'signout' => 'session#destroy'

  resources :people do
    resources :links
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :link_type
  belongs_to :person

  validates_presence_of :url, :name, :link_type
  validate :url_is_valid

  def url_is_valid
    url_re = Regexp.new(/^http[s]?:\/\/[\d|\w]+\.[\w|\d]+.*/)
    email_re = Regexp.new(/^[^@]+@[^@]+/i)
    mailto_re = Regexp.new(/^mailto:/i)
    
    #ditch the mailto first
    self.url.gsub(mailto_re, '')

    mailtype = LinkType.find(7) #hacky -- just get the mail type
    
    unless self.url.match(url_re) || (self.url.match(email_re) and self.link_type_id == mailtype.id)
      @errors.add(:url, "must be a valid URL or email address")
    end
  end
end

app/models/link_type.rb
class LinkType < ActiveRecord::Base
  has_many :links
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :links
  
  validates_presence_of :name
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :login_required

 def login_required
    redirect_to signin_path unless authorized?
  end

  def authorize username, password
    # do login logic here... this is super simple for now
      auth_user, auth_pass = ''
      File.open(RAILS_ROOT + "/login.txt", "r") do |f|
        lines = f.read
        auth_user,auth_pass = lines.chomp.split(":")
      end
      return auth_user == username && auth_pass == password
  end

  def authorized?
    return session[:authorized]
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :person


  # GET /links/new
  # GET /links/new.xml
  def new
    @types = LinkType.all
    @link = @person.links.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
    @types = LinkType.all
  end

  # POST /links
  # POST /links.xml
  def create
    @link = @person.links.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to(@person, :notice => 'Link was successfully created.') }
        format.xml  { render :xml => @link, :status => :created, :location => @link }
      else
        format.html { @types = LinkType.all; render :action => "new" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.xml
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to(@person, :notice => 'Link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.xml
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to @person, :notice => "#{@link.name} was deleted." }
      format.xml  { head :ok }
    end
  end

  def person
    @person = Person.find(params[:person_id])
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new
    @buttontext = "Add Me"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

skip_before_filter :login_required


  def new
  end

  def create
    logger.info (authorize(params[:username],params[:password]).inspect)
    if authorize(params[:username], params[:password])
      session[:authorized] = true
      flash[:notice] = "Logged in!"
      redirect_to people_path
    else
      flash[:error] = "Invalid login/password combination."
      redirect_to signin_path
    end
  end

  def destroy
    reset_session
    flash[:notice] = "Successfully logged out"
    redirect_to signin_path
  end





end

app/helpers/application_helper.rb
module ApplicationHelper

  def flashblock
  # for some reason, this doesn't work 
  #  flash.each do |type,msg|
      render :partial => 'shared/flashblock', :locals => { :type => "notice", :msg => flash[:notice] } unless flash[:notice].nil?
      render :partial => 'shared/flashblock', :locals => { :type => "error", :msg => flash[:error] } unless flash[:error].nil?
      render :partial => 'shared/flashblock', :locals => { :type => "info", :msg => flash[:now] } unless flash[:now].nil?
      
  #  end
  end

  def authorized?
    !session[:authorized].nil? and session[:authorized] == true
  end


end

app/helpers/links_helper.rb
module LinksHelper

  def url_or_email url
    if url.match(/http[s]?:\/\//)
      url
    else
      "mailto:#{url}"
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def login_required
    redirect_to signin_path unless authorized?
  end

  def authorize username, password
    # do login logic here... this is super simple for now
    File.open(RAILS_ROOT + "/login.txt", "r") do |f|
      lines = IO.readlines
      auth_user,auth_pass = lines.split(":")
    end
    auth_user == username && auth_pass == password
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BnrAmhillNet</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
<h1>BNR - zOMG NETWORKING!!111!one!</h1>
<%= flashblock %>
<%= yield %>
</div>
<%= render :partial => 'session/loginout' %>
<a id="hat" href="http://www.bignerdranch.com"><img src="/images/hat.png" /></a>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for([@person, @link]) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
 
  <div class="field"> 
    <%= f.label :link_type_id, "Type" %><br />
    <%= f.select :link_type_id,
                 @types.collect { |t|
                   [ t.type_name, t.id ] } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_icon.html.erb
<li><a class="link <%= icon.link_type.type_name.downcase.gsub(/\s/,'_') %>" href="<%= url_or_email(icon.url) %>" title="<%= icon.name %>"><%= icon.name %></a> <span class="oops">(<%= link_to 'oops', edit_person_link_path(icon.person.id, icon.id) %>)</span></li>

app/views/links/_link.html.erb
<li><a href="<%= link.url %>"><%= link.name %></a> (<%= link_to 'Edit', edit_person_link_path(link.person.id, link.id) %>)</li>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Back', person_path(@person) %> | 
<%= link_to 'Delete this link', person_link_path(@person), :method => :delete %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link.name %></td>
    <td><%= link.url %></td>
    <td><%= link.person_id %></td>
    <td><%= link_to 'Show', person_link %></td>
    <td><%= link_to 'Edit', edit_person_link_path(link) %></td>
    <td><%= link_to 'Destroy', person_link, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_person_link_path %>

app/views/links/new.html.erb
<h3>Add a link to my list</h3>
<p>"Name" will be the link text -- usernames, site titles, whatever you want to put there. For URL, be sure you use the actual http:// prefix (I'm checking!) or a proper e-mail address, in the case of email. The "Website" category is a catchall for anything I didn't think to include (eg. MySpace)</p>
<%= render 'form' %>

<%= link_to 'Nevermind, I don\'t really have another link', person_path(@person) %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @link.name %>
</p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Person:</b>
  <%= @link.person_id %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit "Add Me" %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Nevermind', @person %> |
<%= link_to 'See Everyone Else', people_path %>

app/views/people/index.html.erb
<h2>Nerds</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Links</th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= link_to person.name, person_path(person) %></td>
    <td><%= person.location %></td>
    <td><ul class="home-link"><%= render :partial => 'links/icon', :collection => person.links  %></ul></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Yourself', new_person_path %>

app/views/people/new.html.erb
<h2>Add My Info</h2>

<p>Get it right the first time. Put your name for name (first, last, whatever) and some sort of indication as to where you live on Earth (be as specific or vague as you like, but bear in mind this is technically a public site. No edits after submits. :)</p>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<h3><%= @person.name %></h3>
<p>
  <b>Location:</b>
  <%= @person.location %>
</p>

<ul class="show-link">
<%= render :partial => 'links/icon',
           :collection => @person.links %>
</ul>


<%= link_to 'Add New Link', new_person_link_path(@person) %> |
<%= link_to 'See Everyone Else', people_path %>

app/views/session/_loginout.html.erb
<% if authorized? %>
  <%= link_to 'Sign Out', signout_path, :method => :delete %>
<% end %>

app/views/session/new.html.erb
<%= form_tag :controller => :session, :action=>:create, :method=>:post do %>

<div class="field">
  Username <%= text_field_tag 'username' %><br />
</div>
<div class="field">
  Password <%= password_field_tag 'password' %>
</div>
  <%= submit_tag 'Login!' %>
<% end %>

app/views/shared/_flashblock.html.erb
<p class="flash <%= :type %>"><%= :msg %></p>